### ISSUE TITLE
Introduce Enum for setting the Isolation Level

### ISSUE THREAD

**Issue by ThatOneGuyHavingCode** [munichbughunter/SevenFacette#112]
**Summary**
`kafkaConfig::setIsolationLevel(String)` is hard to use, as the user has to know which values are legal here. An additional class `IsolationLevel` implementing an `Enum` might especially help people new to Kafka. It also shows, which level are supported by 7Facette.
With the additional class, the old method can be deprecated in order to move users to the newer version `kafkaConfig::setIsolationLevel(IsolationLevel)`.

**Motivation**
`kafkaConfig.setIsolationLevel("read_committed");` requires the programmer to read the Kafka documentation in order to understand which values are viable here.
`kafkaConfig.setIsolationLevel(IsolationLevel.xxx);` enables the user to use the IDE's auto-completion feature.

**Describe alternatives you've considered**
Reading https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html and then reverse engineering how 7Facette uses this Kafka feature.

**Additional context**
(none)

**Comment by PDoering** [comment]
Done with release 0.6.5
