### ISSUE TITLE
Optimize build, test and deployment pipeline.

### ISSUE THREAD

**Issue by munichbughunter** [munichbughunter/SevenFacette#129]
Options actual: 
 - Github Actions
 - Circle CI
 - Travis CI

**Comment by 4RuAq7cun** [comment]
- [ ] Remove tests from sonar cloud

- [ ] check if sonar.junit.report can be used

- [ ] sonarbadges

- [ ] optimize pipeline for longliving branches

- [ ] optimize pipeline for push request
