### ISSUE TITLE
KProducer add Header

### ISSUE THREAD

**Issue by MaxRuenz** [munichbughunter/SevenFacette#138]
**Summary**
Add an option to set Kafka message headers within the KProducer

**Motivation**
The Kafka messages in our system contain headers to specify the schema that should be used for deserialization. In order to test that behaviour we need to create such messages, but lack the option to set the header.

**Describe alternatives you've considered**
We checked if there is a way for our system to configure defaults for missing headers per Kafka topic, but only one default that is valid for all topics is supported by spring-kafka. Thus, this is not an option because we need to deserialize topics with different schemata.

**Additional context**

**Comment by MaxRuenz** [comment]
As we have refactored our Kafka handling, we no longer require this functionality

**Comment by romeoro** [comment]
This issue is relevant again, @MaxRuenz and me would love to use that feature as the default spring producer writes headers regarding class information in case of multi schemas on the same topic.
The integration tests would need to mimic that producer behaviour, but can't do so currently.
