### ISSUE TITLE
Introduce creation of FElements from WebElement

### ISSUE THREAD

**Issue by ThatOneGuyHavingCode** [munichbughunter/SevenFacette#140]
**Summary**
As of now, there is no direct way to create FElements directly from WebElements. Together with the missing ability to obtain FElements from a shadow root, we can not test the majority of our GUI.

**Motivation**
We want to test the GUI; this requires accessing the shadow root.

**Describe alternatives you've considered**
Directly using Selenium's WebElement accessed by JS code leads to the expected result.

**Additional context**
`final WebElement shadowRoot = (WebElement) webDriver.executeScript("return arguments[0].shadowRoot", outerTable);`

**Comment by munichbughunter** [comment]
We will switch to playwright.
