### ISSUE TITLE
KConfig#useSASL and KafkaTopicConfig#useSASLAuthentication have different default values

### ISSUE THREAD

**Issue by ThatOneGuyHavingCode** [munichbughunter/SevenFacette#146]
**Prerequisites**
Put an X between the brackets on this line if you have done all of the following:
- [X] Reproduced the problem
- [X] Checked the Wiki for common solutions
- [X] Checked that your issue isn`t already filed
- [X] Checked that there is not already an 7Facette module that provides the described functionality

**Describe the bug**
Looking at `KConfig#useSASL`, the default value is `true`, however when using configuration via facetteConfig, the default value from `KafkaTopicConfig#useSASLAuthentication` is `false`. This behavior is unexpected.

**To Reproduce**

**Expected behavior**
I expect default values to not change when migrating the configuration.

**Comment by munichbughunter** [comment]
Fixed in next version. 
We introduced KafkaTopicConfig where the default value for useSASLAuthentication is false. 

var useSASLAuthentication: Boolean = false,
