### ISSUE TITLE
GenericHttpClient to support HEAD requests

### ISSUE THREAD

**Issue by MaxRuenz** [munichbughunter/SevenFacette#147]
**Summary**
I would like the GernericHTTPClient to support HEAD requests so that I do not have to download large bodies when I only want to test status codes.

**Motivation**
We want to test the availability of video files on a server. As it takes several minutes to download the whole file it would be nice if we can only do an HTTP HEAD request.

**Describe alternatives you've considered**
Download full body that takes several minutes and slows down the test execution by a lot.

**Additional context**
`myGenericHttpClient.head("mypath",new HttpHeader());`

**Comment by munichbughunter** [comment]
Release with version 1.0.2
