### ISSUE TITLE
KConsumer::consume method returns, but is not consuming yet

### ISSUE THREAD

**Issue by ThatOneGuyHavingCode** [munichbughunter/SevenFacette#160]
**Prerequisites**
Put an X between the brackets on this line if you have done all of the following:
- [X] Reproduced the problem
- [X] Checked the Wiki for common solutions
- [X] Checked that your issue isn`t already filed
- [X] Checked that there is not already an 7Facette module that provides the described functionality

**Describe the bug**
```
final KTableTopicConfig topicConfigEssenceImportEssenceImported = new KTableTopicConfig(kafkaConfig);
topicConfigEssenceImportEssenceImported.setKafkaTopic(KafkaConfig.ESSENCEIMPORT_ESSENCEIMPORTED);
essenceImportEssenceCreatedConsumer = topicConfigEssenceImportEssenceImported.createKConsumer(true);
Thread.sleep(1_000); //the consumer needs about one second to actually consume
```

**To Reproduce**
Without the final `Thread.sleep(1_000);` we would miss the relevant message and thus run into a timeout.

**Expected behavior**
When a method named `consume` returns, I expect that the consumer actually consumes, instead of throwing in random periods of waiting trusting that I waited long enough (because I don't want to wait too long and make my tests slow).

**Actual behavior**
Although terminating, it does not consume yet.

**Screenshots**
-/-

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 x64

**Additional context**
Same behavior on the pods.

**Comment by munichbughunter** [comment]
It is fixed.
