### ISSUE TITLE
Error: "No configuration file found" is thrown while creating a Database manually

### ISSUE THREAD

**Issue by 4RuAq7cun** [munichbughunter/SevenFacette#175]
**Prerequisites**
Put an X between the brackets on this line if you have done all of the following:
- [x] Reproduced the problem
- [x] Checked the Wiki for common solutions
- [x] Checked that your issue isn`t already filed
- [x] Checked that there is not already an 7Facette module that provides the described functionality

**Describe the bug**
If using Sevenfacette JVM core version 1.1.2 without using FacetteConfig the Error "No configuration file found" is thrown then trying to create a Database manually: 
**DFactory.createDatabase(dbClientConfig.createDBConfig()**

The error is thrown trying to initialize     private var logger = Logger() in class Database

**Expected behavior**
Logger should be working without SevenFacette config

**Actual behavior**

-> class Database 
-> private var logger = Logger() 
-> class ConfigReader 
-> @JvmStatic
   actual fun getLoggingConfig(): LoggingConfig? = FacetteConfig.log
-> actual fun readConfig() 
	val config = replaceEnvironmentVariables(replaceImports(getConfigFileName().toString()))
-> getConfigFileName()
-> the method can't find any matching file and throws the error "No configuration file found"

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 11.2.3

**Comment by munichbughunter** [comment]
Solved. It was a configuration error no problem with 7Facette
