### ISSUE TITLE
Define Code and Test style

### ISSUE THREAD

**Issue by PDoering** [munichbughunter/SevenFacette#20]
It is important to define and document a code and test style.

**Comment by sBastug** [comment]
Linked to #94

**Comment by munichbughunter** [comment]
Ich habe folgenden Input gefunden: 
https://github.com/marketplace/actions/github-action-for-ktlint
https://github.com/ScaCap/action-ktlint
https://discuss.kotlinlang.org/t/recommended-code-style-tool/3012

https://github.com/detekt/detekt --> Das hier lässt sich anscheinen mit Sonar integrieren
https://github.com/detekt/sonar-kotlin

https://github.com/pinterest/ktlint
