### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by PDoering** [munichbughunter/SevenFacette#94]

**Comment by sBastug** [comment]
1. Create simple Unittests for the testing coverage. Grouped by packages.
- [ ]  config
- [ ]  db
- [ ]  http
- [ ]  utils
2. Testing interfaces and collaboration Moduls.
3. Add more to tests than that the happy cases -> more test cases.
4. Mocking / Dummys etc.

**Comment by sBastug** [comment]
About the code-coverage;
i think it make sense to exclude some code. I mean more code do not have any functionality, like simple getter/setter, enums, except classes and some data classes.
For this porpose i create a overview about the classes, where i look for the questing - Is ther any funculallity or is it only a template for some data to hold.

**Comment by munichbughunter** [comment]
The important parts are done.
